# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- powershell: |
    $files=$(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion))
    echo "Total changed $files files"

- script: |
    lastCommit=$(git log -n 2 --format="%H" | tail -n 1)
    files=$(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion))
    echo "Teste: $lastCommit"
    echo "Teste2: $files"
  displayName: 'Set Previous Commit'

- script: |
    echo "Previous Commit: $(previousCommit)"
  displayName: 'Debug Previous Commit'

- script: |
    git log --oneline
  displayName: 'Print Git Log'

- script: |
    changes=$(git diff $(previousCommit)..HEAD)
    echo "Changes: $changes"
    echo "##vso[task.setvariable variable=folderChanges]$changes"
  displayName: 'Check for Changes in serhiy Folder'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['folderChanges'], ''), contains(variables['folderChanges'], '/'))
  inputs:
    PathtoPublish: 'serhiy/dist'
    ArtifactName: 'frontend'
    publishLocation: 'Container'