# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: PowerShell@2
  displayName: Get GIT Commit-IDs before and after Push
  inputs:
    targetType: 'inline'
    script: |
      # print Information stream
      $InformationPreference = "Continue"

      $headers = @{ Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN" }
      $uri = "$env:SYSTEM_TEAMFOUNDATIONSERVERURI$env:SYSTEM_TEAMPROJECT/_apis/build/builds/$($env:BUILD_BUILDID)/changes?api-version=5.1"
      $changes = Invoke-RestMethod -Method Get -Headers $headers -Uri $uri -Verbose

      if ($changes.count -gt 0) {
          $commit_id_before = $changes.value[$changes.count - 1].id
          $commit_id_after = $changes.value[0].id

          Write-Information "Commit ID before push: $commit_id_before"
          Write-Information "Commit ID after push:  $commit_id_after"

          Write-Host "##vso[task.setvariable variable=GIT_EVENT_BEFORE]$commit_id_before"
          Write-Host "##vso[task.setvariable variable=GIT_EVENT_AFTER]$commit_id_after"
      }
      else {
        Write-Warning "No changes found in Build $buildId"
      }
    pwsh: true
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- powershell: |
    $files=$(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion))
    $temp=$files -split ' '
    $count=$temp.Length
    echo "Total changed $files files"

- script: |
    lastCommit=$(git log -n 2 --format="%H" | tail -n 1)
    files=$(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion))
    echo "Teste: $lastCommit"
    echo "Teste2: $files"
  displayName: 'Set Previous Commit'

- script: |
    echo "Previous Commit: $(previousCommit)"
  displayName: 'Debug Previous Commit'

- script: |
    git log --oneline
  displayName: 'Print Git Log'

- script: |
    changes=$(git diff $(previousCommit)..HEAD)
    echo "Changes: $changes"
    echo "##vso[task.setvariable variable=folderChanges]$changes"
  displayName: 'Check for Changes in serhiy Folder'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['folderChanges'], ''), contains(variables['folderChanges'], '/'))
  inputs:
    PathtoPublish: 'serhiy/dist'
    ArtifactName: 'frontend'
    publishLocation: 'Container'